# Generated by Django 5.1.4 on 2025-06-10 08:28

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriesServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Назва розділу послуг"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                ("seo", models.CharField(blank=True, null=True, verbose_name="сео")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads",
                        verbose_name="Зображення для послуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Послуга категорія",
                "verbose_name_plural": "Послуги категорія",
                "db_table": "categoryservices",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Назва послуги"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "content",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="Контент"
                    ),
                ),
                ("seo", models.CharField(blank=True, null=True, verbose_name="сео")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.categoriesservices",
                        verbose_name="Розділ послуг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Послугу",
                "verbose_name_plural": "Послуги",
                "db_table": "service",
                "ordering": ("id",),
            },
        ),
    ]
