# Generated by Django 5.1.4 on 2025-06-17 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoriesservices",
            options={
                "verbose_name": "Категория услуга",
                "verbose_name_plural": "Категория услуги",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ("id",),
                "verbose_name": "Услугу",
                "verbose_name_plural": "услуги",
            },
        ),
        migrations.AlterField(
            model_name="categoriesservices",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads",
                verbose_name="Изображение для услуги",
            ),
        ),
        migrations.AlterField(
            model_name="categoriesservices",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="название раздела услуг"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="services.categoriesservices",
                verbose_name="Раздел услуг",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Название услуги"
            ),
        ),
    ]
