# Generated by Django 5.1.4 on 2025-06-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_categoriesservices_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriesservices",
            name="description",
            field=models.CharField(
                blank=True, null=True, verbose_name="Краткое описание услуги"
            ),
        ),
        migrations.AlterField(
            model_name="categoriesservices",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Название раздела услуг"
            ),
        ),
    ]
