# Generated by Django 5.1.4 on 2025-06-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_categoriesservices_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="ФИО клиента")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Контактный email"),
                ),
                ("phone", models.CharField(verbose_name="Контактный номер телефона")),
                ("service", models.CharField(verbose_name="ФИО клиента")),
            ],
        ),
    ]
