# Generated by Django 5.1.4 on 2025-06-20 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_orderservice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderservice",
            options={
                "verbose_name": "Заказанная услуга",
                "verbose_name_plural": "Заказанные услуги",
            },
        ),
        migrations.AlterModelTable(
            name="orderservice",
            table="orderservices",
        ),
    ]
