# Generated by Django 5.1.4 on 2025-07-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_alter_orderservice_options_alter_orderservice_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderservice",
            name="service",
            field=models.CharField(verbose_name="Заказанная услуга"),
        ),
    ]
