# Generated by Django 5.1.4 on 2025-07-15 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0006_alter_orderservice_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoriesservices",
            name="image",
        ),
    ]
