# Generated by Django 5.1.4 on 2025-07-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0007_remove_categoriesservices_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriesservices",
            name="seo",
            field=models.CharField(
                blank=True, max_length=160, null=True, verbose_name="сео"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="seo",
            field=models.CharField(
                blank=True, max_length=160, null=True, verbose_name="сео"
            ),
        ),
    ]
