"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import certifi, os
from dotenv import load_dotenv
from pathlib import Path
import dj_database_url


load_dotenv()
os.environ["SSL_CERT_FILE"] = certifi.where()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",

    'cloudinary',
    'cloudinary_storage',

    "whitenoise.runserver_nostatic",

    "debug_toolbar",
    "tinymce",
    "phonenumber_field",

    "main",
    "goods",
    "blog",
    "services",
    "users",
    "carts",
    "orders",
]

MIDDLEWARE = [ 
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    "debug_toolbar.middleware.DebugToolbarMiddleware",

    
]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#DATABASES = {
    #"default": {
        #"ENGINE": "django.db.backends.postgresql",
        #"NAME": "home",
        #"USER": "home",
        #"PASSWORD": "1234",
        #"HOST": "localhost",
        #"PORT": "5432",
    #}
#}
DATABASES = {
    "default": dj_database_url.config(
        default="postgresql://home:1234@localhost:5432/home",  # твоя локальная БД
        conn_max_age=600,  # кэширование соединения
    )
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = 'Europe/Kyiv'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

#STATIC_URL = "static/"

#STATICFILES_DIRS = [
    #BASE_DIR / 'static'
#]

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Whitenoise storage
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = 'media/'

#MEDIA_ROOT = BASE_DIR / 'media'
if DEBUG:
    MEDIA_ROOT = BASE_DIR / 'media'
else:
    MEDIA_ROOT = '/mnt/data/media'

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = 'users.User'
LOGIN_URL ='/user/login/'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = os.getenv("EMAIL_HOST_USER")

TINYMCE_DEFAULT_CONFIG = {
    'height': 600,
    'width': '100%',
    'menubar': 'file edit view insert format tools table help',
    'plugins': (
        'advlist autolink lists link image charmap print preview anchor '
        'searchreplace visualblocks code fullscreen '
        'insertdatetime media table paste code help wordcount emoticons'
        'image link media table code lists fullscreen'
    ),
    'toolbar': (
        'undo redo | styles | bold italic underline strikethrough forecolor backcolor | '
        'alignleft aligncenter alignright alignjustify | '
        'bullist numlist outdent indent | '
        'link image media table emoticons charmap | '
        'insertdatetime preview code fullscreen'
    ),
    'style_formats': [
        {'title': 'Заголовок 1', 'block': 'h1'},
        {'title': 'Заголовок 2', 'block': 'h2'},
        {'title': 'Заголовок 3', 'block': 'h3'},
        {'title': 'Абзац', 'block': 'p'},
        {'title': 'Код', 'inline': 'code'},
        {'title': 'Выделение', 'inline': 'span', 'classes': 'highlight'},
    ],
    'content_style': """
        body { font-family:Arial,sans-serif; font-size:14px; }
        .highlight { background-color: yellow; }
    """,
    'toolbar_mode': 'wrap',  # чтобы не обрезалась панель на маленьком экране
    'contextmenu': 'link image table',
    'branding': False,  # убрать надпись "Powered by Tiny"
    'images_upload_url': '/upload_image/',
    'automatic_uploads': True,
    'images_reuse_filename': True,
    'relative_urls': False,
    'remove_script_host': False,
    'convert_urls': True,
    'content_style': 'img { max-width: 100%; height: auto; }',
}