# Generated by Django 5.1.4 on 2025-07-15 20:11

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriesBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Тематика статей"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "seo",
                    models.CharField(
                        blank=True, max_length=160, null=True, verbose_name="сео"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тема",
                "verbose_name_plural": "Темы",
                "db_table": "categoryblog",
            },
        ),
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название статьи"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Краткое описание статьи"
                    ),
                ),
                ("author", models.CharField(max_length=150, verbose_name="Авторы")),
                (
                    "content",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="Контент"
                    ),
                ),
                (
                    "seo",
                    models.CharField(
                        blank=True, max_length=160, null=True, verbose_name="сео"
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.categoriesblog",
                        verbose_name="Тематика статей",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статью",
                "verbose_name_plural": "Статьи",
                "db_table": "article",
                "ordering": ("id",),
            },
        ),
    ]
