# Generated by Django 5.1.4 on 2025-07-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя клиента")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Контактный email"),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение клиента",
                "verbose_name_plural": "Сообщения от клиентов",
                "db_table": "message",
            },
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(verbose_name="Контактный номер телефона")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Контактный email"),
                ),
                ("address", models.CharField(verbose_name="Адрес офиса")),
                (
                    "instagram",
                    models.CharField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "facebook",
                    models.CharField(blank=True, null=True, verbose_name="Facebook"),
                ),
                (
                    "seo",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="сео стр главная и контакты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт для сайта",
                "verbose_name_plural": "Контакты для сайта",
                "db_table": "contact",
            },
        ),
    ]
